[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
push_comm = "49BqhK92MRb1tpwn5ceLsZZnGoSQaWzYRcPC6doCgUiE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
admin_actions_tests = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/admin_actions.test.ts"
subscription_tests = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/subscription.test.ts"
notification_tests = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/notification.test.ts"
notif_settings_tests = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/notif_settings.test.ts"
