[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
push_comm = "38y1vrywbkV9xNUBQ2rdi6E1PNxj2EhWgakpN3zLtneu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mdzaryabafser/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
